# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/axel/projects/cpplib/cftal

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/axel/projects/cpplib/cftal

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/axel/projects/cpplib/cftal/CMakeFiles /home/axel/projects/cpplib/cftal/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/axel/projects/cpplib/cftal/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cftal

# Build rule for target.
cftal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cftal
.PHONY : cftal

# fast build rule for target.
cftal/fast:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/build
.PHONY : cftal/fast

d_real.o: d_real.cc.o

.PHONY : d_real.o

# target to build an object file
d_real.cc.o:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/d_real.cc.o
.PHONY : d_real.cc.o

d_real.i: d_real.cc.i

.PHONY : d_real.i

# target to preprocess a source file
d_real.cc.i:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/d_real.cc.i
.PHONY : d_real.cc.i

d_real.s: d_real.cc.s

.PHONY : d_real.s

# target to generate assembly for a file
d_real.cc.s:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/d_real.cc.s
.PHONY : d_real.cc.s

math_func.o: math_func.cc.o

.PHONY : math_func.o

# target to build an object file
math_func.cc.o:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/math_func.cc.o
.PHONY : math_func.cc.o

math_func.i: math_func.cc.i

.PHONY : math_func.i

# target to preprocess a source file
math_func.cc.i:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/math_func.cc.i
.PHONY : math_func.cc.i

math_func.s: math_func.cc.s

.PHONY : math_func.s

# target to generate assembly for a file
math_func.cc.s:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/math_func.cc.s
.PHONY : math_func.cc.s

mul_div_32.o: mul_div_32.cc.o

.PHONY : mul_div_32.o

# target to build an object file
mul_div_32.cc.o:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/mul_div_32.cc.o
.PHONY : mul_div_32.cc.o

mul_div_32.i: mul_div_32.cc.i

.PHONY : mul_div_32.i

# target to preprocess a source file
mul_div_32.cc.i:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/mul_div_32.cc.i
.PHONY : mul_div_32.cc.i

mul_div_32.s: mul_div_32.cc.s

.PHONY : mul_div_32.s

# target to generate assembly for a file
mul_div_32.cc.s:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/mul_div_32.cc.s
.PHONY : mul_div_32.cc.s

mul_div_64.o: mul_div_64.cc.o

.PHONY : mul_div_64.o

# target to build an object file
mul_div_64.cc.o:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/mul_div_64.cc.o
.PHONY : mul_div_64.cc.o

mul_div_64.i: mul_div_64.cc.i

.PHONY : mul_div_64.i

# target to preprocess a source file
mul_div_64.cc.i:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/mul_div_64.cc.i
.PHONY : mul_div_64.cc.i

mul_div_64.s: mul_div_64.cc.s

.PHONY : mul_div_64.s

# target to generate assembly for a file
mul_div_64.cc.s:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/mul_div_64.cc.s
.PHONY : mul_div_64.cc.s

v2f64.o: v2f64.cc.o

.PHONY : v2f64.o

# target to build an object file
v2f64.cc.o:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/v2f64.cc.o
.PHONY : v2f64.cc.o

v2f64.i: v2f64.cc.i

.PHONY : v2f64.i

# target to preprocess a source file
v2f64.cc.i:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/v2f64.cc.i
.PHONY : v2f64.cc.i

v2f64.s: v2f64.cc.s

.PHONY : v2f64.s

# target to generate assembly for a file
v2f64.cc.s:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/v2f64.cc.s
.PHONY : v2f64.cc.s

v4f32.o: v4f32.cc.o

.PHONY : v4f32.o

# target to build an object file
v4f32.cc.o:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/v4f32.cc.o
.PHONY : v4f32.cc.o

v4f32.i: v4f32.cc.i

.PHONY : v4f32.i

# target to preprocess a source file
v4f32.cc.i:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/v4f32.cc.i
.PHONY : v4f32.cc.i

v4f32.s: v4f32.cc.s

.PHONY : v4f32.s

# target to generate assembly for a file
v4f32.cc.s:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/v4f32.cc.s
.PHONY : v4f32.cc.s

v4f64.o: v4f64.cc.o

.PHONY : v4f64.o

# target to build an object file
v4f64.cc.o:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/v4f64.cc.o
.PHONY : v4f64.cc.o

v4f64.i: v4f64.cc.i

.PHONY : v4f64.i

# target to preprocess a source file
v4f64.cc.i:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/v4f64.cc.i
.PHONY : v4f64.cc.i

v4f64.s: v4f64.cc.s

.PHONY : v4f64.s

# target to generate assembly for a file
v4f64.cc.s:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/v4f64.cc.s
.PHONY : v4f64.cc.s

v8f32.o: v8f32.cc.o

.PHONY : v8f32.o

# target to build an object file
v8f32.cc.o:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/v8f32.cc.o
.PHONY : v8f32.cc.o

v8f32.i: v8f32.cc.i

.PHONY : v8f32.i

# target to preprocess a source file
v8f32.cc.i:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/v8f32.cc.i
.PHONY : v8f32.cc.i

v8f32.s: v8f32.cc.s

.PHONY : v8f32.s

# target to generate assembly for a file
v8f32.cc.s:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/v8f32.cc.s
.PHONY : v8f32.cc.s

v8f64.o: v8f64.cc.o

.PHONY : v8f64.o

# target to build an object file
v8f64.cc.o:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/v8f64.cc.o
.PHONY : v8f64.cc.o

v8f64.i: v8f64.cc.i

.PHONY : v8f64.i

# target to preprocess a source file
v8f64.cc.i:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/v8f64.cc.i
.PHONY : v8f64.cc.i

v8f64.s: v8f64.cc.s

.PHONY : v8f64.s

# target to generate assembly for a file
v8f64.cc.s:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/v8f64.cc.s
.PHONY : v8f64.cc.s

vec_traits.o: vec_traits.cc.o

.PHONY : vec_traits.o

# target to build an object file
vec_traits.cc.o:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/vec_traits.cc.o
.PHONY : vec_traits.cc.o

vec_traits.i: vec_traits.cc.i

.PHONY : vec_traits.i

# target to preprocess a source file
vec_traits.cc.i:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/vec_traits.cc.i
.PHONY : vec_traits.cc.i

vec_traits.s: vec_traits.cc.s

.PHONY : vec_traits.s

# target to generate assembly for a file
vec_traits.cc.s:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/vec_traits.cc.s
.PHONY : vec_traits.cc.s

x86_ops_1.o: x86_ops_1.cc.o

.PHONY : x86_ops_1.o

# target to build an object file
x86_ops_1.cc.o:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/x86_ops_1.cc.o
.PHONY : x86_ops_1.cc.o

x86_ops_1.i: x86_ops_1.cc.i

.PHONY : x86_ops_1.i

# target to preprocess a source file
x86_ops_1.cc.i:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/x86_ops_1.cc.i
.PHONY : x86_ops_1.cc.i

x86_ops_1.s: x86_ops_1.cc.s

.PHONY : x86_ops_1.s

# target to generate assembly for a file
x86_ops_1.cc.s:
	$(MAKE) -f CMakeFiles/cftal.dir/build.make CMakeFiles/cftal.dir/x86_ops_1.cc.s
.PHONY : x86_ops_1.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cftal"
	@echo "... d_real.o"
	@echo "... d_real.i"
	@echo "... d_real.s"
	@echo "... math_func.o"
	@echo "... math_func.i"
	@echo "... math_func.s"
	@echo "... mul_div_32.o"
	@echo "... mul_div_32.i"
	@echo "... mul_div_32.s"
	@echo "... mul_div_64.o"
	@echo "... mul_div_64.i"
	@echo "... mul_div_64.s"
	@echo "... v2f64.o"
	@echo "... v2f64.i"
	@echo "... v2f64.s"
	@echo "... v4f32.o"
	@echo "... v4f32.i"
	@echo "... v4f32.s"
	@echo "... v4f64.o"
	@echo "... v4f64.i"
	@echo "... v4f64.s"
	@echo "... v8f32.o"
	@echo "... v8f32.i"
	@echo "... v8f32.s"
	@echo "... v8f64.o"
	@echo "... v8f64.i"
	@echo "... v8f64.s"
	@echo "... vec_traits.o"
	@echo "... vec_traits.i"
	@echo "... vec_traits.s"
	@echo "... x86_ops_1.o"
	@echo "... x86_ops_1.i"
	@echo "... x86_ops_1.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

