test :
	cd golang; make test
	cd java; make test testsp
	cd purec; make test testsp
	cd sseavx; make test testsp

clean :
	rm -f *~
	cd golang; make clean
	cd java; make clean
	cd purec; make clean
	cd sseavx; make clean
	cd tester; make clean
