test :
	cd java; make test testsp
	cd purec; make test testsp
	cd sseavx; make testsse2 testavx

clean :
	rm -f *~
	cd java; make clean
	cd purec; make clean
	cd sseavx; make clean
	cd tester; make clean
